django/config/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.DieticianIndexView.as_view(), name='index'),
    path(
         'dietician/<int:pk>/',
         views.DieticianChooseAppointmentView.as_view(),
         name='dietician_detail'),
    path(
        'dietician/<int:dietician_id>/appointment/<int:day>/<int:hour>/',
        views.dietician_personal_data,
        name='dietician_personal_data'),
    path('thanks', views.thanks, name='thanks'),
    path(
        'appointments',
        views.AppointmentList.as_view(),
        name='appointment_list'),
]

django/core/models.py
import logging

from django.core.mail import send_mail
from django.db import models
from django.template.loader import get_template

logger = logging.getLogger('django')


class Dietician(models.Model):
    EMPTY = 0
    MR = 1
    MS = 2
    PREFIXES = (
        (EMPTY, ''),
        (MR, 'dietetyk'),
        (MS, 'dietetyczka'),
    )
    PREFIXES_DICT = {values[0]: values[1] for values in PREFIXES}

    prefix = models.IntegerField(choices=PREFIXES, default=EMPTY)
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)

    def __str__(self):
        return '{} {} {}'.format(
            self.get_prefix_display(), self.name, self.surname)


class Appointment(models.Model):
    DAYS = (
        (1, 'pon'),
        (2, 'wt'),
        (3, 'sr'),
        (4, 'cz'),
        (5, 'pt'),
        (6, 'sb'),
        (7, 'nd'),
    )
    HOURS = []
    for hour in range(0, 24):
        for minute in (0, 30):
            HOURS.append((
                int('{:02d}{:02d}'.format(hour, minute)),
                '{:02d}:{:02d}'.format(hour, minute),))
    CONFIRMATION_SUBJECT = "Potwierdzenie wizyty w systemie"

    dietician = models.ForeignKey(Dietician, on_delete=models.CASCADE)
    day = models.IntegerField(choices=DAYS)
    hour = models.IntegerField(choices=HOURS)
    name = models.CharField(max_length=128)
    email = models.EmailField()

    def send_confirmation(self):
        sender = 'from@example.com'
        recipients = [self.email]
        data = {
            'name': self.name,
            'day': self.get_day_display(),
            'hour': self.get_hour_display(),
            'dietician': self.dietician,
        }
        plaintext = get_template('email/appointment_confirmation.txt')
        text_content = plaintext.render(data)
        send_mail(self.CONFIRMATION_SUBJECT, text_content, sender, recipients)

    @classmethod
    def get_appointment_for_dietician(cls, dietician):
        appointment = {}
        for day, day_name in cls.DAYS:
            appointment[day] = {
                'day': day_name,
                'hours': {}
            }
            for hour, hour_name in cls.HOURS:
                appointment_hour = {
                    'hour': hour_name,
                    'available': True
                }
                appointment[day]['hours'][hour] = appointment_hour
        taken_appointments = cls.objects.filter(dietician=dietician)
        for taken_appointment in taken_appointments:
            appointment[
                taken_appointment.day]['hours'][taken_appointment.hour][
                'available'] = False
        return appointment

    class Meta:
        unique_together = ('dietician', 'day', 'hour')

    def __str__(self):
        data = {
            'day': self.get_day_display(),
            'hour': self.get_hour_display(),
            'name': self.name,
            'email': self.email,
        }
        return '{day} - {hour} {name} <{email}>'.format(**data)

django/core/forms.py
import logging

from django import forms

logger = logging.getLogger('django')


class AppointmentForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=128)
    email = forms.EmailField(label='Your email')
    dietician_id = forms.IntegerField(widget=forms.widgets.HiddenInput())
    day = forms.IntegerField(widget=forms.widgets.HiddenInput())
    hour = forms.IntegerField(widget=forms.widgets.HiddenInput())


# class AppointmentOldForm(forms.ModelForm):
#     class Meta:
#         model = Appointment
#         fields = ['dietician', 'day', 'hour', 'name', 'email']

django/core/views.py
import logging
from pprint import pformat

from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .const import APPOINTMENT_INVALID_FORM, APPOINTMENT_TAKEN_MSG, \
    APPOINTMENT_UNKNOWN_ERROR
from .forms import AppointmentForm
from .models import Dietician, Appointment

logger = logging.getLogger('django')


class DieticianIndexView(generic.ListView):
    template_name = 'dietician/index.html'

    def get_queryset(self):
        return Dietician.objects.order_by('surname')[:10]


class DieticianChooseAppointmentView(generic.DetailView):
    model = Dietician
    template_name = 'dietician/choose_appointment.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['appointments'] = \
            Appointment.get_appointment_for_dietician(self.object)
        return self.render_to_response(context)


class DieticianPersonalDataView(generic.DetailView):
    model = Dietician
    template_name = 'dietician/personal_data.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['appointments'] = \
            Appointment.get_appointment_for_dietician(self.object)
        return self.render_to_response(context)


def dietician_personal_data(request, dietician_id, day, hour):
    is_ajax = request.is_ajax()
    context = {'error': ''}
    name = ''
    email = ''
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            dietician_id = form.cleaned_data['dietician_id']
            dietician = Dietician.objects.get(pk=dietician_id)
            data = {
                'dietician': dietician,
                'day': form.cleaned_data['day'],
                'hour': form.cleaned_data['hour'],
                'name': form.cleaned_data['name'],
                'email': form.cleaned_data['email'],
            }
            appointment = Appointment(**data)
            try:
                appointment.save()
                appointment.send_confirmation()
                if is_ajax:
                    return JsonResponse({
                        'status': True,
                        'redirect': reverse('core:thanks'),
                    })
                else:
                    return HttpResponseRedirect(reverse('core:thanks'))
            except IntegrityError:
                error = APPOINTMENT_TAKEN_MSG
                logger.exception(error)
            except Exception:
                error = APPOINTMENT_UNKNOWN_ERROR
                logger.exception(error)
            if is_ajax:
                return JsonResponse({
                    'status': False,
                    'error': error, },
                    status=400,
                )
            else:
                context['error'] = error
                name = form.cleaned_data['name']
                email = form.cleaned_data['email']
        else:
            if is_ajax:
                response = JsonResponse({
                    'status': False,
                    'error': APPOINTMENT_INVALID_FORM,
                    'errors': form.errors, },
                    status=400,
                )
                return response
            logger.error('invalid form')
            logger.debug(pformat(form.errors))
            context['form'] = form
        return render(request, 'dietician/personal_data.html', context)

    form = AppointmentForm()
    form.fields['dietician_id'].initial = dietician_id
    form.fields['day'].initial = day
    form.fields['hour'].initial = hour
    form.fields['name'].initial = name
    form.fields['email'].initial = email
    context['form'] = form
    dietician = Dietician.objects.get(pk=dietician_id)
    data = {
        'dietician': dietician,
        'day': day,
        'hour': hour,
    }
    appointment = Appointment(**data)
    context['day'] = appointment.get_day_display()
    context['hour'] = appointment.get_hour_display()
    context['dietician'] = Dietician.objects.get(pk=dietician_id)
    return render(request, 'dietician/personal_data.html', context)


def thanks(request):
    message = 'Dziekujemy za rezerwację.'
    return render(request, 'dietician/thanks.html', {'message': message})


class AppointmentList(generic.ListView):
    model = Appointment

    def get_queryset(self):
        return Appointment.objects.order_by(
            'day', 'hour', 'dietician__surname')[:10]

django/core/templates/dietician/choose_appointment.html
{% extends 'base.html' %}

{% block title %}
    Terminy wizyt
{% endblock %}

{% block main %}
    {{ dietician }} - Wybierz termin:

    <div class="container">
        <div class="row">
            {% for day_id, term in appointments.items %}
                <div class="col">
                    {{ term.day }}
                    <ul>
                        {% for hour_id, hour in term.hours.items %}
                            <li>
                                {% if hour.available %}
                                    <span class="free_appointment">
                                        <a href="{% url 'core:dietician_personal_data' dietician.id day_id hour_id %}">{{ hour.hour }}</a>
                                    </span>
                                {% else %}
                                    <span class="taken_appointment">{{ hour.hour }}</span>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

django/core/templates/dietician/index.html
{% extends 'base.html' %}

{% block title %}
    Dietetycy
{% endblock %}

{% block main %}
    <ul>
        {% for dietician in object_list %}
            <li>
                <a href="{% url 'core:dietician_detail' dietician.id %}">{{ dietician }}</a>
            </li>
        {% empty %}
            <li>Brak dietetyków</li>
        {% endfor %}
    </ul>
{% endblock %}

django/core/templates/dietician/personal_data.html
{% extends 'base.html' %}

{% block title %}
    rezerwuj już dziś :-)
{% endblock %}

{% block main %}
    {{ dietician }} - {{ day }} - {{ hour }}
    <div id="error">{% if error %}{{ error }}{%  endif %}</div>
    <form action="#" method="post" id="user-appointment-form">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit">

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
    </form>
{% endblock %}

django/core/templates/dietician/thanks.html
{% extends 'base.html' %}

{% block title %}
    Dziękujemy
{% endblock %}

{% block main %}
    {{ message }}
{% endblock %}