django/config/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.DieticianIndexView.as_view(), name='index'),
    path(
         'dietician/<int:pk>/',
         views.DieticianChooseAppointmentView.as_view(),
         name='dietician_detail'),
    path(
        'dietician/<int:dietician_id>/appointment/<int:day>/<int:hour>/',
        views.dietician_personal_data,
        name='dietician_personal_data'),
    path('thanks', views.thanks, name='thanks'),
    path(
        'appointments',
        views.AppointmentList.as_view(),
        name='appointment_list'),
]

django/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>{% block title %}kcalmar{% endblock %}</title>
    <style>
    </style>
</head>
<body>
<div class="container">
    <nav class="nav">
        <div class="navbar-brand">
            <a href="/" class="nav-link">kcalmar</a>
        </div>
    </nav>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-9">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm3 offset-sm-1">
            {% block sidebar %}
                <ul>
                    <li><a href="{% url 'core:appointment_list' %}">appointment_list</a>
                    </li>
                </ul>
            {% endblock %}
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% load static %}
    <script src="{% static "/scripts/main.js" %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>